# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coursedetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7)),
                ('name', models.CharField(max_length=50)),
                ('Slot', models.IntegerField(blank=True, null=True)),
                ('credit', models.IntegerField(blank=True, null=True)),
                ('tutorial', models.BooleanField(default=False)),
                ('tutorialSlot', models.CharField(max_length=5)),
            ],
        ),
    ]
