# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20171015_0304'),
        ('courses', '0002_auto_20170930_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='PrescribedStudyHours',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.profile'),
        ),
    ]
