# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursedetail_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetail',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.profile'),
        ),
    ]
