# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20171015_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetail',
            name='Student',
            field=models.ManyToManyField(blank=True, related_name='Student_List', to='profiles.profile'),
        ),
    ]
