# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Timetable', '0023_auto_20171011_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='dailyStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SelfStudy', models.IntegerField(default=0)),
                ('ExtraCurricularsTime', models.IntegerField(default=0)),
                ('ExtraStudyTime', models.IntegerField(default=0)),
                ('ClassTiming', models.IntegerField(default=0)),
                ('MiscellaneousTime', models.IntegerField(default=0)),
                ('linkedDay', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Timetable.DailySched')),
            ],
        ),
    ]
