# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20170926_1941'),
        ('Timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Description', models.CharField(blank=True, max_length=300)),
                ('Venue', models.CharField(blank=True, max_length=100)),
                ('StartTime', models.DateTimeField(blank=True, null=True)),
                ('EndTime', models.DateTimeField(blank=True, null=True)),
                ('DeadLine', models.DateTimeField(blank=True, null=True)),
                ('Priority', models.CharField(blank=True, choices=[('1', 'Normal'), ('2', 'Preferred'), ('3', 'Important'), ('4', 'Indespensable')], default='1', max_length=25)),
                ('Type', models.CharField(blank=True, choices=[('A', 'Official Classes'), ('B', 'Study Acads'), ('C', 'Extra Study'), ('D', 'ExtraCurriculars'), ('E', 'Misc.')], default='', max_length=25)),
                ('TimeSettings', models.CharField(blank=True, choices=[('A', 'Duration Fixed'), ('B', 'Duration and Timing Fixed'), ('C', 'Variable')], default='C', max_length=25)),
                ('UserProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
