# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0003_auto_20170929_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slots',
            name='EndTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='slots',
            name='StartTime',
            field=models.TimeField(),
        ),
    ]
