# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0004_auto_20170930_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots',
            name='EventConnected',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Timetable.Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='TimeSettings',
            field=models.CharField(blank=True, choices=[('A', 'Duration Fixed'), ('B', 'Duration and Timing Fixed'), ('C', 'Variable')], default='B', max_length=25),
        ),
    ]
