# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0006_auto_20171001_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ScheduledEndTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='ScheduledStartTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
