# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0007_auto_20171002_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EndDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='EndTime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='StartDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='StartTime',
            field=models.TimeField(null=True),
        ),
    ]
