# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0009_auto_20171007_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Duration',
            field=models.CharField(choices=[('1', 'Half Hour'), ('2', 'One Hour'), ('3', 'One and Half Hour'), ('4', 'Two Hour')], default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='event',
            name='Priority',
            field=models.CharField(blank=True, choices=[('1', 'Normal'), ('2', 'Preferred'), ('3', 'Important'), ('4', 'Indespensable')], default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='event',
            name='TimeSettings',
            field=models.CharField(blank=True, choices=[('A', 'Duration Fixed'), ('B', 'Duration and Timing Fixed'), ('C', 'Variable')], default='B', max_length=5),
        ),
        migrations.AlterField(
            model_name='event',
            name='Type',
            field=models.CharField(choices=[('A', 'Official Classes'), ('B', 'Study Acads'), ('C', 'Extra Study'), ('D', 'ExtraCurriculars'), ('E', 'Misc.')], default='E', max_length=5),
        ),
    ]
