# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 18:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0011_auto_20171008_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='StartDate',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='StartTime',
            field=models.TimeField(null=True),
        ),
    ]
