# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 19:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0012_auto_20171008_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='DeadLineDate',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='EndDate',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
