# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0013_auto_20171008_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='DeadLineTime',
            field=models.TimeField(null=True),
        ),
    ]
