# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 09:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0014_auto_20171008_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='DeadLineDate',
            field=models.DateField(blank=True, default=datetime.date(2017, 10, 11), null=True),
        ),
    ]
