# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 18:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0017_auto_20171009_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='DeadLineDate',
            field=models.DateField(blank=True, default=datetime.date(2017, 10, 13), null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='TimeSettings',
            field=models.CharField(blank=True, choices=[('B', 'Fixed Timing'), ('C', 'Variable Timing')], default='B', max_length=5),
        ),
    ]
