# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 18:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0018_auto_20171010_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='DeadLineDate',
            field=models.DateField(default=datetime.date(2017, 10, 13), null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='Priority',
            field=models.CharField(choices=[('1', 'Normal'), ('2', 'Preferred'), ('3', 'Important'), ('4', 'Indespensable')], default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='event',
            name='TimeSettings',
            field=models.CharField(choices=[('B', 'Fixed Timing'), ('C', 'Variable Timing')], default='B', max_length=5),
        ),
    ]
