# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0017_auto_20171009_2244'),
        ('Timetable', '0020_auto_20171010_0024'),
    ]

    operations = [
    ]
