# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 19:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0021_merge_20171010_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='DeadLineDate',
            field=models.DateField(blank=True, default=datetime.date(2017, 10, 13), null=True),
        ),
    ]
