# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 11:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0024_merge_20171011_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='DeadLineDate',
            field=models.DateField(blank=True, default=datetime.date(2017, 10, 16), null=True),
        ),
    ]
