# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 11:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_profile_instructor'),
        ('Timetable', '0025_auto_20171013_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Description', models.CharField(blank=True, max_length=300)),
                ('StartTime', models.TimeField(null=True)),
                ('StartDate', models.DateField(default=datetime.date.today, null=True)),
                ('ExpectedDuration', models.CharField(choices=[('1', 'Half Hour'), ('2', 'One Hour'), ('3', 'One and Half Hour'), ('4', 'Two Hour')], default='1', max_length=5)),
                ('DeadLineTime', models.TimeField(blank=True, default='23:30:00', null=True)),
                ('DeadLineDate', models.DateField(blank=True, default=datetime.date(2017, 10, 16), null=True)),
                ('UserProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Description', models.CharField(blank=True, max_length=300)),
                ('Venue', models.CharField(blank=True, max_length=100)),
                ('StartTime', models.TimeField(null=True)),
                ('StartDate', models.DateField(default=datetime.date.today, null=True)),
                ('PreparationRequired', models.BooleanField(default=False)),
                ('PreparationDuration', models.CharField(choices=[('1', 'Half Hour'), ('2', 'One Hour'), ('3', 'One and Half Hour'), ('4', 'Two Hour')], default='1', max_length=5)),
                ('EndTime', models.TimeField(null=True)),
                ('EndDate', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('Compulsory', models.BooleanField(default=True)),
                ('UserProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
