# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 01:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0026_instructorassignment_instructorclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='DeadLineDate',
            field=models.DateField(blank=True, default=datetime.date(2017, 10, 17), null=True),
        ),
        migrations.AlterField(
            model_name='instructorassignment',
            name='DeadLineDate',
            field=models.DateField(blank=True, default=datetime.date(2017, 10, 17), null=True),
        ),
        migrations.AlterField(
            model_name='instructorclass',
            name='PreparationDuration',
            field=models.CharField(blank=True, choices=[('1', 'Half Hour'), ('2', 'One Hour'), ('3', 'One and Half Hour'), ('4', 'Two Hour')], default='1', max_length=5, null=True),
        ),
    ]
