# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0027_auto_20171014_0827'),
        ('Timetable', '0025_auto_20171013_1633'),
    ]

    operations = [
    ]
