# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0028_merge_20171014_0208'),
        ('Timetable', '0027_auto_20171014_0643'),
    ]

    operations = [
    ]
