# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 18:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0032_auto_20171016_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='CreaterId',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='CreaterType',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='DeadLineDate',
            field=models.DateField(blank=True, default=datetime.date(2017, 10, 20), null=True),
        ),
        migrations.AlterField(
            model_name='instructorassignment',
            name='DeadLineDate',
            field=models.DateField(blank=True, default=datetime.date(2017, 10, 20), null=True),
        ),
    ]
