# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0034_merge_20171017_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorassignment',
            name='StudentData',
            field=models.CharField(default='$', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='instructorexam',
            name='StudentData',
            field=models.CharField(default='$', max_length=250, null=True),
        ),
    ]
