# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0035_auto_20171017_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='CreaterId',
            new_name='CreatorId',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='CreaterType',
            new_name='CreatorType',
        ),
    ]
