# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 02:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0037_auto_20171018_0517'),
        ('Timetable', '0037_auto_20171019_0155'),
    ]

    operations = [
    ]
