# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0038_auto_20171019_1320'),
        ('Timetable', '0038_merge_20171019_0742'),
    ]

    operations = [
    ]
