# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0040_auto_20171020_0332'),
        ('Timetable', '0039_merge_20171020_1451'),
    ]

    operations = [
    ]
