# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0040_auto_20171020_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Autogenerated',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
