# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0041_event_autogenerated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Autogenerated',
        ),
    ]
