# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0042_remove_event_autogenerated'),
        ('Timetable', '0041_merge_20171020_1932'),
    ]

    operations = [
    ]
