# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0044_auto_20171021_0016'),
        ('Timetable', '0044_auto_20171021_0017'),
    ]

    operations = [
    ]
