# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0041_merge_20171021_0740'),
        ('Timetable', '0045_merge_20171021_0152'),
    ]

    operations = [
    ]
