# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0046_merge_20171021_1513'),
        ('Timetable', '0047_auto_20171022_0732'),
        ('Timetable', '0045_merge_20171021_0213'),
    ]

    operations = [
    ]
