# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0050_merge_20171023_0218'),
        ('Timetable', '0050_auto_20171022_1418'),
    ]

    operations = [
    ]
