# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0052_auto_20171023_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Duration',
            field=models.CharField(choices=[('1', 'Half Hour'), ('2', 'One Hour'), ('3', 'One and Half Hour'), ('4', 'Two Hour'), ('5', 'Two and Half Hour'), ('6', 'Three Hour'), ('8', 'Four Hour'), ('10', 'Five Hours'), ('12', 'Six Hours')], default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='instructorassignment',
            name='ExpectedDuration',
            field=models.CharField(choices=[('1', 'Half Hour'), ('2', 'One Hour'), ('3', 'One and Half Hour'), ('4', 'Two Hour'), ('5', 'Two and Half Hour'), ('6', 'Three Hour'), ('8', 'Four Hour'), ('10', 'Five Hours'), ('12', 'Six Hours')], default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='instructorexam',
            name='PreparationDuration',
            field=models.CharField(blank=True, choices=[('1', 'Half Hour'), ('2', 'One Hour'), ('3', 'One and Half Hour'), ('4', 'Two Hour'), ('5', 'Two and Half Hour'), ('6', 'Three Hour'), ('8', 'Four Hour'), ('10', 'Five Hours'), ('12', 'Six Hours')], default='1', max_length=5, null=True),
        ),
    ]
