# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 04:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0054_auto_20171024_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='DeadLineDate',
            field=models.DateField(blank=True, default=datetime.date(2017, 10, 28), null=True),
        ),
        migrations.AlterField(
            model_name='instructorassignment',
            name='DeadLineDate',
            field=models.DateField(blank=True, default=datetime.date(2017, 10, 28), null=True),
        ),
    ]
