# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20171010_1433'),
        ('Event_suggestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='UserProfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
