# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sleepChoice',
            field=models.CharField(choices=[('A', '6 hours'), ('B', '7 hours'), ('C', '8 hours')], default='B', max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='studyChoice',
            field=models.CommaSeparatedIntegerField(choices=[('1', 'Day'), ('2', 'Evening'), ('3', 'Night'), ('4', 'Late Night')], default=3, max_length=4),
        ),
    ]
