# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20170923_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='crickenthu',
            field=models.BooleanField(default=False),
        ),
    ]
