# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_crickenthu'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='NBAenthu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='footballenthu',
            field=models.BooleanField(default=False),
        ),
    ]
