# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20170926_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lastSuggestion',
            field=models.DateTimeField(null=True),
        ),
    ]
