# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_lastsuggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lastSuggestion',
            field=models.DateField(null=True),
        ),
    ]
