# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20171011_0002'),
        ('profiles', '0010_auto_20171011_0127'),
    ]

    operations = [
    ]
