# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 10:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_merge_20171011_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lastSuggestion',
            field=models.DateField(default=datetime.date(2017, 10, 8), null=True),
        ),
    ]
