# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20171013_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instructor',
            field=models.BooleanField(default=False),
        ),
    ]
