# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 20:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20171016_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lastSuggestion',
            field=models.DateField(default=datetime.date(2017, 10, 12), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='studyChoice',
            field=models.CharField(choices=[('1', 'Day'), ('3', 'Night'), ('4', 'Late Night')], default='3', max_length=1),
        ),
    ]
