# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20171016_2334'),
        ('profiles', '0019_auto_20171017_0001'),
    ]

    operations = [
    ]
