# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20171017_0156'),
        ('profiles', '0019_auto_20171017_1417'),
    ]

    operations = [
    ]
