# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_merge_20171019_0742'),
        ('profiles', '0022_auto_20171019_1320'),
    ]

    operations = [
    ]
