# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_auto_20171020_0332'),
        ('profiles', '0023_merge_20171020_1452'),
    ]

    operations = [
    ]
