# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_auto_20171021_0017'),
        ('profiles', '0026_auto_20171021_0016'),
    ]

    operations = [
    ]
