# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_auto_20171022_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
