# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_merge_20171021_1513'),
        ('profiles', '0031_auto_20171022_0817'),
        ('profiles', '0027_merge_20171021_0213'),
    ]

    operations = [
    ]
