# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0034_auto_20171021_2300'),
        ('profiles', '0032_merge_20171022_0841'),
    ]

    operations = [
    ]
