# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 04:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0038_auto_20171024_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lastSuggestion',
            field=models.DateField(default=datetime.date(2017, 10, 20), null=True),
        ),
    ]
